### ISSUE TITLE
Convince Your Boss page

### ISSUE THREAD

**Issue by sophialucero** [tjmonsi/ffc-pwdo#26]
References 
http://pwdo.github.io/ffc9-measure/ 
https://drive.google.com/drive/u/0/folders/0B3BQZooe26_7aDE5c0dmamZOREU

**Comment by tjmonsi** [comment]
https://2018.formfunctionclass.com/convince

Will add link to it in menu

**Comment by tjmonsi** [comment]
@sophialucero there's no convince your boss on menu. What color should i use?

**Comment by sophialucero** [comment]
@tjmonsi Updated Menu on Measure here: https://pwdo.github.io/ffc9-measure/#artboard0

* If magka issue sa space it's ok to remove Scrapbook muna 

![menu](https://user-images.githubusercontent.com/3439620/41552941-da50b79e-7362-11e8-95a0-b56377143ba1.png)

**Comment by sophialucero** [comment]
^ Ok na yung symbol alignment, yung pag-add na lang sa menu :)
