### ISSUE TITLE
Spacing & typography

### ISSUE THREAD

**Issue by sophialucero** [tjmonsi/ffc-pwdo#28]
Please check the Sketch measure prototype for more info. Basically TLDR is we want the text to breathe more and be aligned more consistently.

- [x] Max-width of text blocks should be approximately 720px

- [x] Increase spacing between list items that are more complex (e.g. see "Want to win a ticket?" section) 

- [x] Increase spacing between sections 

- [x] Paragraph and list text should have the same margins on all sides inside the boxes (e.g. see difference in alignment between the "3+1 Free", "Visayas & Mindanao", "Tech Community" boxes)

- [x] In the boxes, increase space between h3 headings and the body text (lists/desciptions) (e.g. see "Tech Community" box)

**Comment by sophialucero** [comment]
Did some adjustments to CSS that should address a bit of this @tjmonsi

**Comment by tjmonsi** [comment]
Updated the site. Please check and close

**Comment by sophialucero** [comment]
Can see changes now, thank you!
