### ISSUE TITLE
Box list alignment

### ISSUE THREAD

**Issue by sophialucero** [tjmonsi/ffc-pwdo#35]
List alignment changed: 

<img width="666" alt="box list alignment" src="https://user-images.githubusercontent.com/3439620/41593992-796ab410-73f4-11e8-9780-e81a32aed268.png">

**Comment by tjmonsi** [comment]
Safari to no?

**Comment by tjmonsi** [comment]
@sophialucero it is working on mine. But lemme check tonight yung site sa IOS

**Comment by sophialucero** [comment]
Good sa iOS!

**Comment by sophialucero** [comment]
Getting this in Firefox 61 MacOS @tjmonsi 

<img width="558" alt="box-list-firefox" src="https://user-images.githubusercontent.com/3439620/42302809-cdf9ab8c-804f-11e8-9387-70f3ed42ab66.png">

**Comment by tjmonsi** [comment]
Will check in a bit
