### ISSUE TITLE
Session page subtitle

### ISSUE THREAD

**Issue by sophialucero** [tjmonsi/ffc-pwdo#36]
h2 text should all be Acumin Pro 

<img width="773" alt="session h2" src="https://user-images.githubusercontent.com/3439620/41598326-7a5c6be4-7402-11e8-8fa2-45f8d7f88f81.png">

**Comment by tjmonsi** [comment]
![image](https://user-images.githubusercontent.com/2645718/41705879-f10b71f2-756c-11e8-98f6-81c605a1299b.png)
Kinda weird. I'll try to check this out...

**Comment by tjmonsi** [comment]
Hopefully it is fixed. please check and close @sophialucero

**Comment by sophialucero** [comment]
Looks ok na
